github.dismiss_out_of_range_messages

detekt_dir = "**/detekt.xml"
Dir[detekt_dir].each do |file_name|
    kotlin_detekt.report_file = file_name
    kotlin_detekt.skip_gradle_task = true
    kotlin_detekt.detekt
end

require 'oga'
require 'tempfile'

IGNORED_LINT_IDS = %w[GradleDependency NewerVersionAvailable GradlePluginVersion].freeze

lint_dir = "**/build/reports/lint-results*.xml"
Dir[lint_dir].each do |file_name|
  doc = Oga.parse_xml(File.read(file_name))
  doc.xpath('//issue').select { |i| IGNORED_LINT_IDS.include?(i.get('id')) }
                      .each(&:remove)
  tmp = Tempfile.new(['lint-filtered', '.xml'])
  begin
    tmp.write(doc.to_xml)
    tmp.close
    android_lint.report_file = tmp.path
    android_lint.skip_gradle_task = true
    android_lint.lint(inline_mode: true)
  ensure
    tmp.unlink
  end
end

if File.exist?('build.log')
  File.readlines('build.log')
    .select { |line| line.match?(/^w:\s+/) }
    .each { |line| warn line.strip }
end

junit_output_dir = "**/test-results/**/*.xml"
Dir[junit_output_dir].each do |file_name|
  junit.parse(file_name)
  junit.show_skipped_tests = true
  junit.report
end

unless status_report[:warnings].empty?
  markdown "### Warnings\n" + status_report[:warnings].map { |w| "- #{w}" }.join("\n")
  fail "Build failed due to warnings"
end
