name: Master Snapshot Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build, run checks, release SNAPSHOT to Maven Central
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
        cache: 'gradle'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
        bundler-cache: true
#    - name: Cache Gradle
#      if: always()
#      uses: actions/cache@v2
#      with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#        restore-keys: |
#          ${{ runner.os }}-gradle-
    - name: Assemble release
      run: |
        echo "::add-matcher::.github/gradle-java-matcher.json"
        echo "::add-matcher::.github/kotlin-error-matcher.json"
        echo "::add-matcher::.github/kotlin-warning-matcher.json"
        ./gradlew clean assembleRelease -Dorg.gradle.daemon=false
    - name: Run all checks and create coverage report
      run: |
        ./gradlew check jacocoTestReport
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Publish to Maven Central Snapshots repo
      run: |
        ./gradlew publishAllPublicationsToMavenCentralSnapshotsRepository -Possrh.username=${{ secrets.OSSRH_USERNAME }} -Possrh.password="${{ secrets.OSSRH_PASSWORD }}"
