name: Publish a release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build, run checks, release to Maven Central
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Cache Gradle
        if: always()
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build, test, coverage, upload to Maven Central
        run: |
          echo "::add-matcher::.github/gradle-java-matcher.json"
          echo "::add-matcher::.github/kotlin-error-matcher.json"
          echo "::add-matcher::.github/kotlin-warning-matcher.json"
          ./gradlew assembleRelease check jacocoTestReport javadocJar sourcesJar publishAllPublicationsToMavenCentralReleasesRepository --no-daemon -Prelease=true -Possrh.username=${{ secrets.OSSRH_USERNAME }} -Possrh.password="${{ secrets.OSSRH_PASSWORD }}"
      - name: Trigger Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/rxreactor*.?ar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
